### ISSUE TITLE
Сделать шапку

### ISSUE THREAD

**Issue by wanku-x** [openworld-community/peredelano-landing#15]
Делаем каталог `./src/layout` в котором будет `index.ts` для экспорта наших лейаутов и будет папка `Header`. В папке `Header` будут `Header.tsx`, `Header.module.css`, `index.ts` (по аналогии с Button).

Первую итерацию предлагаю сделать без бургер меню. Тратить время на выпадашку, которая будет навигировать по одной странице - ну мягко говоря глупо. Если ее не будет на мобиле - никто не умрет, ибо это лендос.

## Примерная разметка:

```html
<header class="header">
  <div class="header__container">
    <a class="header__logo-link" href="/" aria-label="На главную страницу">
      <img class="header__logo" src="..." aria-hidden>
    </a>
  
    <nav class="header__nav">
      <ul class="header__nav-list">
        <li class="header__nav-item">
          <a class="header__nav-link" href="#">...</a>
        </li>
        ....
      </ul>
    </nav>
  </div>
</header>
```

На ссылку логотипа нужно навесить aria-label, чтобы пользователи с ограниченными возможностями (далее ОВ) могли понять что это за ссылка, ибо текста внутри нет.

Само лого скрыть для них, оно им не нужно - вешаем атрибут aria-hidden

##  Примерные стили

```css
.header {
  padding-top: ...;
  padding-bottom: ...;

  &__container {
    margin-left: auto;
    margin-right: auto;

    padding-left: var(--gap);
    padding-right: var(--gap);

    width: var(--container-width);

    display: flex;
    flex-wrap: wrap;
    gap: 1--gap;
  }

  &__logo-link { ... }

  &__logo {
    display: block;

    height: ...;
  }

  &__nav {
    /* Пока вот так костыльно, вообще нужно делать хак с visually-hidden, но тут навигация тупо по странице, а пользователи с ОВ и так могут навигироваться по заголовкам */
    display: none;

    @media (--md) {
      display: block;
    }
  }

  &__nav-list {
      /* Я не помню точно какие там дефолтные отступы у списка, обнули только те, что нам не нужны */
      margin-top: 0;
      margin-bottom: 0;
      padding-left: 0;

      display: flex;
      gap: var(--gap);
      flex-wrap: wrap;

      list-style-type: none;
  }

  &__nav-item { ... }

  &__nav-link {
    font: var(--typo-t2); /* Какой стиль текста уже зависит от дизайн системы */
    color: var(--color-...) /* Какой-то цвет из дизайн системы */

    &:hover { ... }
    &:active { ... }
    &:focus { ... }
  }
}
```

## Интеграция

Впихнуть шапку в `./src/app/layout.tsx`
