### ISSUE TITLE
Сделать Hero блок

### ISSUE THREAD

**Issue by wanku-x** [openworld-community/peredelano-landing#16]
Создаем папку `./src/app/_components`. В ней будут компоненты главной страницы. Делаем `index.ts` файл для экспорта компонентов из этой папки. Создаем каталог `Hero` в котором будут файлы `Hero.tsx`, `Hero.module.css`, `index.ts`.

## Примерная разметка

```html
<section class="hero">
  <div class="hero__container">
    <div class="hero__content">
      <h1 class="hero__title">...</h1>
      <p class="hero__description">...</p>
    </div>
    <img class="hero__image" src="..." aria-hidden />
  </div>
</section>
```

Для картинки делаем aria-hidden потому что это не контентная картинка, и ее не должны видеть пользователи со скринридеров

## Примерные стили

```css
.hero {
  padding-top: ...;
  padding-bottom: ...;

  &__container {
    margin-left: auto;
    margin-right: auto;
    padding-left: var(--gap);
    padding-right: var(--gap);

    width: var(--container-width);
    min-height: calc(100vh - ...); /* Сложи высоту шапки с padding-top и padding-bottom у hero */

    display: flex;
    flex-wrap: wrap;
    gap: var(--gap);
    align-items: center;
  }

  &__content {
    flex-grow: 1;
  }

  &__image {
    display: none;

    @media (--md) {
      display: block;

      width: ...;

      flex-shrink: 0;
      flex-grow: 0;
    }
  }

  &__title {
    margin-bottom: ...--px;

    font: var(--typo-h1);
    color: var(...);
  }

  &__description {
    font: var(--typo-t1);
    color: var(...);
  }
}
```

## Интеграция

Запихать компонент в `./src/app/page.tsx`
