### ISSUE TITLE
Сделать библиотеку компонентов

### ISSUE THREAD

**Issue by wanku-x** [openworld-community/peredelano-landing#4]
- [x] Типографика
- [x] Цвета
- [x] Кнопки
- [ ] Ссылки
- [ ] Иконки

# Типографика

Она находится в файле `./src/styles/typography.css`.

Сначала определиться с дизайнером, что меняем в типографике по сравнению с той, что есть в [дизайн системе](https://www.figma.com/file/EhE4J7lLbztoqR2P4rO2Wo/%D0%A7%D0%B5%D1%80%D0%BD%D0%BE%D0%B2%D0%B8%D0%BA-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%8B?type=design&node-id=672-305&t=UTrlzYJT48YCAL8F-0).

Если ограничиваемся только сменой шрифта, то меняем название шрифта. Наш шрифт вроде есть в Google Fonts, поэтому лучше его подрубить пот так: https://nextjs.org/docs/app/building-your-application/optimizing/fonts#google-fonts

Если шрифт будет другой и не из Google Fonts, то так: https://nextjs.org/docs/app/building-your-application/optimizing/fonts#local-fonts. Шрифта в формате woff2 будет достаточно. Шрифты лучше убрать в каталог `./src/fonts`

Если меняем количество начертаний, то определяемся, какие оставляем, какие нет. Ненужные - удаляем, при необходимости переименовываем

Если меняем размеры, то меняем размеры

# Цвета

Поскольку сайт делается изначально в темной теме, в целом допустимо их называть а-ля `black`, `white`, `orange`. Ну и время поджимает, поэтому проще поступить так, чем называть цвета по назначению, потому что придется весь макет ресерчить и разбираться какой цвет для чего используется

```css
:root {
  --color-black: ...;
  --color-white: ...;
  --color-blue: ...;
  --color-blue-light: ...; /* Например для ховера кнопки */
  --color-blue-dark: ...; /* Например для состояния active кнопки или фокуса */
   ...
}
```

Цвета расположить в файле `./src/styles/colors.css` и подключить в `./src/styles/global.css`.

# Кнопки

Я уже сделал бойлерплейт для кнопки в папке `./src/components/Button`. Компонент там полиморфный и у него есть атрибут `as` в который можно передать название тега или компонент (прям как в styled-components).

Перед тем как начать, лучше всего сразу разместить эту кнопку без атрибута `as` и c атрибутом `as="a"` чтобы проверять стили сразу на кнопках и ссылках.

Я сейчас вижу 2 варианта кнопки: outlined и contained. C цветами не очень понятно, но допустим их два. Что примерно можно попытаться сделать:

```css
.button {
  /* Общие стили для всех начертаний кнопок */

  &--default {
    --color-button-bg: ...;
    --color-button-bg-hover: ...;
    --color-button-bg-active: ...;
    --color-button-text: ...;
    --color-button-outline: ...;
  }

  &--primary {
    --color-button-bg: ...;
    --color-button-bg-hover: ...;
    --color-button-bg-active: ...;
    --color-button-text: ...;
    --color-button-outline: ...;
  }
  
  &--contained {
    border-color: var(--color-button-bg);
    background-color: var(--color-button-bg);
    color: var(--color-button-text);

    &:hover {
      border-color: var(--color-button-bg-hover);
      background-color: var(--color-button-bg-hover);
    }
    &:active {
      border-color: var(--color-button-bg-active);
      background-color: var(--color-button-bg-active);
    }
    &:focus {
      outline: 2px solid var(--color-button-outline);
    }
  }

  &--outlined {
    border-color: var(--color-button-bg);
    background-color: transparent;
    color: var(--color-button-text);
    
    &:hover {
      background-color: var(--color-button-bg);
    }
    &:active {
      border-color: var(--color-button-bg-active);
      background-color: var(--color-button-bg-active);
    }
    &:focus {
      outline: 2px solid var(--color-button-outline);
    }
  }
}
```

Ну а затем в самой кнопке с помощью CVA прокинуть эти классы: https://cva.style/docs/getting-started

# Ссылки

Создать папку `./src/components/Link`, и в ней замутить полиморфный компонент ссылки. В файле `./src/types/polymorphicComponent.ts` есть все необходимое и есть ссылка с объяснением. Также пример можно глянуть в файле `./src/components/Button/Button.tsx`. По дефолту это будет компонент Link из NextJS. А так же может быть тегом `a` или `button`. Все три варианта стоит протестировать при стилизации. Скорее всего ссылка будет с одним вариантом начертания, поэтому там должно хватить одно класса, и состояния hover, active, focus.

Не забудь прокинуть этот компонент в `./src/components/index.ts`.

# Иконки

Сейчас их в дизайне нет. Но учитывая количество ссылок в шапке, возможно будет бургер меню. И соответсвенно будет и иконка бургера. Поэтому на всякий случай пишу. Проследи за дизайнером, чтобы у иконки был охранительный контейнер, и попроси эту иконку вынести в отдельные компоненты, и чтобы вдальнейшем иконки собирались по их образу и подобию. Также попроси компонент как-то обозвать нормально. Это название ты будешь использовать в коде. Если названия будут расходиться, то потом обязательно появится точно такая же иконка но с другим названием)

Иконки эти сохрани себе локально, и прогони их через [SVGO](https://jakearchibald.github.io/svgomg/). Порежь все что можно и нельзя, выстави качество такое, чтобы иконку не сильно косоебило. Сохраняй пожатые SVG и сохраняй себе

Компонент иконок сделай в `./src/components/Icon`. Ну и там уже сделай компонент с атрибутом а-ля `name` и в зависимости от названия подставляй нужную SVGшку. Еще рекомендую сделать у всех иконок `fill="currentColor"`. Тогда они будут иметь цвет как у свойства `color` у ближайшего родителя. Очень удобно, особенно в кнопках. Выставил color, и цвет текста и иконки совпадают. Нужно поменять - меняешь color у самой иконки.
